// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFfivxKWyulJlaGLmbb23oPEjUPzlGk8A',
    appId: '1:33226716048:web:6d87883c5cb928985f7915',
    messagingSenderId: '33226716048',
    projectId: 'employeeattendancesystem-402f9',
    authDomain: 'employeeattendancesystem-402f9.firebaseapp.com',
    storageBucket: 'employeeattendancesystem-402f9.firebasestorage.app',
    measurementId: 'G-KDSP0K2RMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJp8sMastfpcdwy_cJBk9wl-a-Q4nuRuE',
    appId: '1:33226716048:android:3b7c07f88c8438585f7915',
    messagingSenderId: '33226716048',
    projectId: 'employeeattendancesystem-402f9',
    storageBucket: 'employeeattendancesystem-402f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZwOE-_mhNchbIX4B3wb--EEHw7LI2Eko',
    appId: '1:33226716048:ios:e257d2bc1a7c90f95f7915',
    messagingSenderId: '33226716048',
    projectId: 'employeeattendancesystem-402f9',
    storageBucket: 'employeeattendancesystem-402f9.firebasestorage.app',
    iosBundleId: 'com.example.attendenceManagementSystem',
  );

}